/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsBenchmarksRouteImport } from './routes/docs/benchmarks'
import { Route as DocsInstallationRouteImport } from './routes/docs/installation'
import { Route as DocsTokensRouteImport } from './routes/docs/tokens'
import { Route as DocsComponentsIndexRouteImport } from './routes/docs/components/index'
import { Route as DocsComponentsAccordionRouteImport } from './routes/docs/components/accordion'
import { Route as DocsComponentsBadgeRouteImport } from './routes/docs/components/badge'
import { Route as DocsComponentsButtonRouteImport } from './routes/docs/components/button'
import { Route as DocsComponentsCardRouteImport } from './routes/docs/components/card'
import { Route as DocsComponentsCodePillRouteImport } from './routes/docs/components/code-pill'
import { Route as DocsComponentsDefinitionBlockRouteImport } from './routes/docs/components/definition-block'
import { Route as DocsComponentsDialogRouteImport } from './routes/docs/components/dialog'
import { Route as DocsComponentsInputRouteImport } from './routes/docs/components/input'
import { Route as DocsComponentsLayoutRouteImport } from './routes/docs/components/layout'
import { Route as DocsComponentsLeaderboardRouteImport } from './routes/docs/components/leaderboard'
import { Route as DocsComponentsProgressBarRouteImport } from './routes/docs/components/progress-bar'
import { Route as DocsComponentsSliderRouteImport } from './routes/docs/components/slider'
import { Route as DocsComponentsTableRouteImport } from './routes/docs/components/table'
import { Route as DocsComponentsTabsRouteImport } from './routes/docs/components/tabs'
import { Route as DocsComponentsToastRouteImport } from './routes/docs/components/toast'
import { Route as DocsComponentsTypographyRouteImport } from './routes/docs/components/typography'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsBenchmarksRoute = DocsBenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTokensRoute = DocsTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsIndexRoute = DocsComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsAccordionRoute = DocsComponentsAccordionRouteImport.update({
  id: '/components/accordion',
  path: '/components/accordion',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsBadgeRoute = DocsComponentsBadgeRouteImport.update({
  id: '/components/badge',
  path: '/components/badge',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsButtonRoute = DocsComponentsButtonRouteImport.update({
  id: '/components/button',
  path: '/components/button',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsCardRoute = DocsComponentsCardRouteImport.update({
  id: '/components/card',
  path: '/components/card',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsCodePillRoute = DocsComponentsCodePillRouteImport.update({
  id: '/components/code-pill',
  path: '/components/code-pill',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsDefinitionBlockRoute =
  DocsComponentsDefinitionBlockRouteImport.update({
    id: '/components/definition-block',
    path: '/components/definition-block',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsComponentsDialogRoute = DocsComponentsDialogRouteImport.update({
  id: '/components/dialog',
  path: '/components/dialog',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsInputRoute = DocsComponentsInputRouteImport.update({
  id: '/components/input',
  path: '/components/input',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsLayoutRoute = DocsComponentsLayoutRouteImport.update({
  id: '/components/layout',
  path: '/components/layout',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsLeaderboardRoute =
  DocsComponentsLeaderboardRouteImport.update({
    id: '/components/leaderboard',
    path: '/components/leaderboard',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsComponentsProgressBarRoute =
  DocsComponentsProgressBarRouteImport.update({
    id: '/components/progress-bar',
    path: '/components/progress-bar',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsComponentsSliderRoute = DocsComponentsSliderRouteImport.update({
  id: '/components/slider',
  path: '/components/slider',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsTableRoute = DocsComponentsTableRouteImport.update({
  id: '/components/table',
  path: '/components/table',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsTabsRoute = DocsComponentsTabsRouteImport.update({
  id: '/components/tabs',
  path: '/components/tabs',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsToastRoute = DocsComponentsToastRouteImport.update({
  id: '/components/toast',
  path: '/components/toast',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsTypographyRoute =
  DocsComponentsTypographyRouteImport.update({
    id: '/components/typography',
    path: '/components/typography',
    getParentRoute: () => DocsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/benchmarks': typeof DocsBenchmarksRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/tokens': typeof DocsTokensRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/components/accordion': typeof DocsComponentsAccordionRoute
  '/docs/components/badge': typeof DocsComponentsBadgeRoute
  '/docs/components/button': typeof DocsComponentsButtonRoute
  '/docs/components/card': typeof DocsComponentsCardRoute
  '/docs/components/code-pill': typeof DocsComponentsCodePillRoute
  '/docs/components/definition-block': typeof DocsComponentsDefinitionBlockRoute
  '/docs/components/dialog': typeof DocsComponentsDialogRoute
  '/docs/components/input': typeof DocsComponentsInputRoute
  '/docs/components/layout': typeof DocsComponentsLayoutRoute
  '/docs/components/leaderboard': typeof DocsComponentsLeaderboardRoute
  '/docs/components/progress-bar': typeof DocsComponentsProgressBarRoute
  '/docs/components/slider': typeof DocsComponentsSliderRoute
  '/docs/components/table': typeof DocsComponentsTableRoute
  '/docs/components/tabs': typeof DocsComponentsTabsRoute
  '/docs/components/toast': typeof DocsComponentsToastRoute
  '/docs/components/typography': typeof DocsComponentsTypographyRoute
  '/docs/components/': typeof DocsComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/benchmarks': typeof DocsBenchmarksRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/tokens': typeof DocsTokensRoute
  '/docs': typeof DocsIndexRoute
  '/docs/components/accordion': typeof DocsComponentsAccordionRoute
  '/docs/components/badge': typeof DocsComponentsBadgeRoute
  '/docs/components/button': typeof DocsComponentsButtonRoute
  '/docs/components/card': typeof DocsComponentsCardRoute
  '/docs/components/code-pill': typeof DocsComponentsCodePillRoute
  '/docs/components/definition-block': typeof DocsComponentsDefinitionBlockRoute
  '/docs/components/dialog': typeof DocsComponentsDialogRoute
  '/docs/components/input': typeof DocsComponentsInputRoute
  '/docs/components/layout': typeof DocsComponentsLayoutRoute
  '/docs/components/leaderboard': typeof DocsComponentsLeaderboardRoute
  '/docs/components/progress-bar': typeof DocsComponentsProgressBarRoute
  '/docs/components/slider': typeof DocsComponentsSliderRoute
  '/docs/components/table': typeof DocsComponentsTableRoute
  '/docs/components/tabs': typeof DocsComponentsTabsRoute
  '/docs/components/toast': typeof DocsComponentsToastRoute
  '/docs/components/typography': typeof DocsComponentsTypographyRoute
  '/docs/components': typeof DocsComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/benchmarks': typeof DocsBenchmarksRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/tokens': typeof DocsTokensRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/components/accordion': typeof DocsComponentsAccordionRoute
  '/docs/components/badge': typeof DocsComponentsBadgeRoute
  '/docs/components/button': typeof DocsComponentsButtonRoute
  '/docs/components/card': typeof DocsComponentsCardRoute
  '/docs/components/code-pill': typeof DocsComponentsCodePillRoute
  '/docs/components/definition-block': typeof DocsComponentsDefinitionBlockRoute
  '/docs/components/dialog': typeof DocsComponentsDialogRoute
  '/docs/components/input': typeof DocsComponentsInputRoute
  '/docs/components/layout': typeof DocsComponentsLayoutRoute
  '/docs/components/leaderboard': typeof DocsComponentsLeaderboardRoute
  '/docs/components/progress-bar': typeof DocsComponentsProgressBarRoute
  '/docs/components/slider': typeof DocsComponentsSliderRoute
  '/docs/components/table': typeof DocsComponentsTableRoute
  '/docs/components/tabs': typeof DocsComponentsTabsRoute
  '/docs/components/toast': typeof DocsComponentsToastRoute
  '/docs/components/typography': typeof DocsComponentsTypographyRoute
  '/docs/components/': typeof DocsComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/benchmarks'
    | '/docs/installation'
    | '/docs/tokens'
    | '/docs/'
    | '/docs/components/accordion'
    | '/docs/components/badge'
    | '/docs/components/button'
    | '/docs/components/card'
    | '/docs/components/code-pill'
    | '/docs/components/definition-block'
    | '/docs/components/dialog'
    | '/docs/components/input'
    | '/docs/components/layout'
    | '/docs/components/leaderboard'
    | '/docs/components/progress-bar'
    | '/docs/components/slider'
    | '/docs/components/table'
    | '/docs/components/tabs'
    | '/docs/components/toast'
    | '/docs/components/typography'
    | '/docs/components/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/benchmarks'
    | '/docs/installation'
    | '/docs/tokens'
    | '/docs'
    | '/docs/components/accordion'
    | '/docs/components/badge'
    | '/docs/components/button'
    | '/docs/components/card'
    | '/docs/components/code-pill'
    | '/docs/components/definition-block'
    | '/docs/components/dialog'
    | '/docs/components/input'
    | '/docs/components/layout'
    | '/docs/components/leaderboard'
    | '/docs/components/progress-bar'
    | '/docs/components/slider'
    | '/docs/components/table'
    | '/docs/components/tabs'
    | '/docs/components/toast'
    | '/docs/components/typography'
    | '/docs/components'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/benchmarks'
    | '/docs/installation'
    | '/docs/tokens'
    | '/docs/'
    | '/docs/components/accordion'
    | '/docs/components/badge'
    | '/docs/components/button'
    | '/docs/components/card'
    | '/docs/components/code-pill'
    | '/docs/components/definition-block'
    | '/docs/components/dialog'
    | '/docs/components/input'
    | '/docs/components/layout'
    | '/docs/components/leaderboard'
    | '/docs/components/progress-bar'
    | '/docs/components/slider'
    | '/docs/components/table'
    | '/docs/components/tabs'
    | '/docs/components/toast'
    | '/docs/components/typography'
    | '/docs/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/benchmarks': {
      id: '/docs/benchmarks'
      path: '/benchmarks'
      fullPath: '/docs/benchmarks'
      preLoaderRoute: typeof DocsBenchmarksRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/tokens': {
      id: '/docs/tokens'
      path: '/tokens'
      fullPath: '/docs/tokens'
      preLoaderRoute: typeof DocsTokensRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/': {
      id: '/docs/components/'
      path: '/components'
      fullPath: '/docs/components/'
      preLoaderRoute: typeof DocsComponentsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/accordion': {
      id: '/docs/components/accordion'
      path: '/components/accordion'
      fullPath: '/docs/components/accordion'
      preLoaderRoute: typeof DocsComponentsAccordionRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/badge': {
      id: '/docs/components/badge'
      path: '/components/badge'
      fullPath: '/docs/components/badge'
      preLoaderRoute: typeof DocsComponentsBadgeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/button': {
      id: '/docs/components/button'
      path: '/components/button'
      fullPath: '/docs/components/button'
      preLoaderRoute: typeof DocsComponentsButtonRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/card': {
      id: '/docs/components/card'
      path: '/components/card'
      fullPath: '/docs/components/card'
      preLoaderRoute: typeof DocsComponentsCardRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/code-pill': {
      id: '/docs/components/code-pill'
      path: '/components/code-pill'
      fullPath: '/docs/components/code-pill'
      preLoaderRoute: typeof DocsComponentsCodePillRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/definition-block': {
      id: '/docs/components/definition-block'
      path: '/components/definition-block'
      fullPath: '/docs/components/definition-block'
      preLoaderRoute: typeof DocsComponentsDefinitionBlockRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/dialog': {
      id: '/docs/components/dialog'
      path: '/components/dialog'
      fullPath: '/docs/components/dialog'
      preLoaderRoute: typeof DocsComponentsDialogRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/input': {
      id: '/docs/components/input'
      path: '/components/input'
      fullPath: '/docs/components/input'
      preLoaderRoute: typeof DocsComponentsInputRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/layout': {
      id: '/docs/components/layout'
      path: '/components/layout'
      fullPath: '/docs/components/layout'
      preLoaderRoute: typeof DocsComponentsLayoutRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/leaderboard': {
      id: '/docs/components/leaderboard'
      path: '/components/leaderboard'
      fullPath: '/docs/components/leaderboard'
      preLoaderRoute: typeof DocsComponentsLeaderboardRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/progress-bar': {
      id: '/docs/components/progress-bar'
      path: '/components/progress-bar'
      fullPath: '/docs/components/progress-bar'
      preLoaderRoute: typeof DocsComponentsProgressBarRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/slider': {
      id: '/docs/components/slider'
      path: '/components/slider'
      fullPath: '/docs/components/slider'
      preLoaderRoute: typeof DocsComponentsSliderRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/table': {
      id: '/docs/components/table'
      path: '/components/table'
      fullPath: '/docs/components/table'
      preLoaderRoute: typeof DocsComponentsTableRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/tabs': {
      id: '/docs/components/tabs'
      path: '/components/tabs'
      fullPath: '/docs/components/tabs'
      preLoaderRoute: typeof DocsComponentsTabsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/toast': {
      id: '/docs/components/toast'
      path: '/components/toast'
      fullPath: '/docs/components/toast'
      preLoaderRoute: typeof DocsComponentsToastRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/typography': {
      id: '/docs/components/typography'
      path: '/components/typography'
      fullPath: '/docs/components/typography'
      preLoaderRoute: typeof DocsComponentsTypographyRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsBenchmarksRoute: typeof DocsBenchmarksRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsTokensRoute: typeof DocsTokensRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsComponentsAccordionRoute: typeof DocsComponentsAccordionRoute
  DocsComponentsBadgeRoute: typeof DocsComponentsBadgeRoute
  DocsComponentsButtonRoute: typeof DocsComponentsButtonRoute
  DocsComponentsCardRoute: typeof DocsComponentsCardRoute
  DocsComponentsCodePillRoute: typeof DocsComponentsCodePillRoute
  DocsComponentsDefinitionBlockRoute: typeof DocsComponentsDefinitionBlockRoute
  DocsComponentsDialogRoute: typeof DocsComponentsDialogRoute
  DocsComponentsInputRoute: typeof DocsComponentsInputRoute
  DocsComponentsLayoutRoute: typeof DocsComponentsLayoutRoute
  DocsComponentsLeaderboardRoute: typeof DocsComponentsLeaderboardRoute
  DocsComponentsProgressBarRoute: typeof DocsComponentsProgressBarRoute
  DocsComponentsSliderRoute: typeof DocsComponentsSliderRoute
  DocsComponentsTableRoute: typeof DocsComponentsTableRoute
  DocsComponentsTabsRoute: typeof DocsComponentsTabsRoute
  DocsComponentsToastRoute: typeof DocsComponentsToastRoute
  DocsComponentsTypographyRoute: typeof DocsComponentsTypographyRoute
  DocsComponentsIndexRoute: typeof DocsComponentsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsBenchmarksRoute: DocsBenchmarksRoute,
  DocsInstallationRoute: DocsInstallationRoute,
  DocsTokensRoute: DocsTokensRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsComponentsAccordionRoute: DocsComponentsAccordionRoute,
  DocsComponentsBadgeRoute: DocsComponentsBadgeRoute,
  DocsComponentsButtonRoute: DocsComponentsButtonRoute,
  DocsComponentsCardRoute: DocsComponentsCardRoute,
  DocsComponentsCodePillRoute: DocsComponentsCodePillRoute,
  DocsComponentsDefinitionBlockRoute: DocsComponentsDefinitionBlockRoute,
  DocsComponentsDialogRoute: DocsComponentsDialogRoute,
  DocsComponentsInputRoute: DocsComponentsInputRoute,
  DocsComponentsLayoutRoute: DocsComponentsLayoutRoute,
  DocsComponentsLeaderboardRoute: DocsComponentsLeaderboardRoute,
  DocsComponentsProgressBarRoute: DocsComponentsProgressBarRoute,
  DocsComponentsSliderRoute: DocsComponentsSliderRoute,
  DocsComponentsTableRoute: DocsComponentsTableRoute,
  DocsComponentsTabsRoute: DocsComponentsTabsRoute,
  DocsComponentsToastRoute: DocsComponentsToastRoute,
  DocsComponentsTypographyRoute: DocsComponentsTypographyRoute,
  DocsComponentsIndexRoute: DocsComponentsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
